services:
  backend:
    environment:
      SPRING_PROFILES_ACTIVE: $SPRING_PROFILES_ACTIVE
      OKTA_TESTING_DISABLEHTTPSCHECK: $OKTA_TESTING_DISABLEHTTPSCHECK
      OKTA_API_KEY: $OKTA_API_KEY
      OKTA_OAUTH2_CLIENT_ID: $OKTA_OAUTH2_CLIENT_ID
      SMARTY_AUTH_ID: $SMARTY_AUTH_ID
      SMARTY_AUTH_TOKEN: $SMARTY_AUTH_TOKEN
      WIREMOCK_URL: $WIREMOCK_URL
      SPRING_LIQUIBASE_ENABLED: "true"
      GIT_DISCOVERY_ACROSS_FILESYSTEM: 1
  frontend:
    environment:
      REACT_APP_OKTA_URL: $WIREMOCK_URL
      REACT_APP_BASE_URL: https://localhost.simplereport.gov
      REACT_APP_BACKEND_URL: https://localhost.simplereport.gov/api
      PUBLIC_URL: /app/
      REACT_APP_OKTA_ENABLED: "true"
      REACT_APP_DISABLE_MAINTENANCE_BANNER: "true"
      GIT_DISCOVERY_ACROSS_FILESYSTEM: 1
  nginx:
    hostname: localhost.simplereport.gov
  mailhog:
    profiles:
      - donotstart